# -*- coding: utf-8 -*-
"""BAP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HBtX7ck8op-P-TkOZGWrlFRBpYJTieC3
"""

from sklearn.linear_model import LinearRegression

import numpy as np

import pandas as pd

df = pd.read_csv('test_data.csv')

df.head()

x = df[['x1', 'x2']]
y = df['y']

x = np.array(x)
y = np.array(y)

model = LinearRegression()

model.fit(x,y)

model.predict([[130.838816, 9332660000]])

model.get_params()

"""Find the Minimum X1 (Average Grant) to have a postive 0.5% increase in Fertility Rate"""

val = 0 #Fertility Rate
target = 1.14 * 1.01 #Target Fertility Rate, Start @ 2019 (Fertility Rate = 1.4) * 0.5% Increase
x2_value_list = [9191310000, 10248170000, 10958080000, 11660560000, 12382280000, 12968520000] # Index 0 = 2020

year = 2020
for i in range(len(x2_value_list)):
  x2_value = x2_value_list[i]
  x1_value = 0 # Average Grant Amount (Reset)
  while val <= target:
    val = model.predict([[x1_value, x2_value]])
    x1_value = x1_value + 0.01
    # Average Grant Amount, Increment of 1 cent

  print('%d : %.2f, %d - Fertility Rate = %f.4' % (year, x1_value, x2_value, val))
  year += 1
  target = target * 1.01